<?php

namespace app\modules\en\controllers;

use app\models\AllusapartsMenu;
use yii\web\Controller;
use yii\web\HttpException;

/**
 * Default controller for the `en` module
 */
class DefaultController extends Controller
{
    public function init()
    {
        \Yii::$app->params['lang'] = 'en';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public $layout = 'main';
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionBrand($brand){
        $brandInfo = [];
        $result = AllusapartsMenu::activeQueryMenu()
            ->where([
                'm.url' => '/brands/'.$brand,
                'language' => \Yii::$app->params['lang']
            ])
            ->asArray()
            ->all();

        if (empty($result)) throw new HttpException(
            404,
            'Запрошенная страница не найдена'
        );

        foreach($result as $r){
            $brandInfo['text'] = $r['text'];
            $brandInfo['h1'] = $r['h1'];
            $brandInfo['title'] = $r['title'];
            $brandInfo['description'] = $r['description'];
            $brandInfo['url'] = $r['url'];
            $brandInfo['name'] = $r['name'];
            if (isset($r['link'])) $brandInfo['links'][] = $r['link'];
        }
        return $this->render('@app/views/site/rubrands', [
            'brand' => $brand,
            'brandInfo' => $brandInfo
        ]);
    }

    public function actionPage($main){
        \Yii::$app->params['lang'] = 'en';
        $menu = AllusapartsMenu::activeQueryMenu()
            ->where([
                'm.url' => '/page/'.$main,
                'language' => \Yii::$app->params['lang']
            ])
            ->asArray()
            ->one();
        return $this->render('@app/views/page/main', [
            'menu' => $menu
        ]);
    }
}
